# Generated by Django 3.0.7 on 2021-03-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='proof_of_payment',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
