# Generated by Django 3.0.7 on 2021-08-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_proof_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('K', 'Kosmetik'), ('KT', 'Kesehatan')], max_length=2),
        ),
    ]
